version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: simak_db
    environment:
      POSTGRES_USER: simak_user
      POSTGRES_PASSWORD: simak_password
      POSTGRES_DB: simak_vokasi
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: simak_backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://simak_user:simak_password@db:5432/simak_vokasi
      - PORT=3000
      - JWT_SECRET=simak_vokasi_secret_key_123456
      - CORS_ORIGIN=*
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    container_name: simak_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  pgdata:
